name: Build and Publish

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags (e.g., v0.1.0)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install build twine setuptools-scm

      # Step 4: Build the package
      - name: Build package
        run: python -m build

      # Step 5: Publish to PyPI using Trusted Publisher Workflow
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      # Step 6: Create GitHub Release using gh CLI
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} ./dist/* \
            --title "Release ${{ github.ref_name }}" \
            --notes "This is an automated release."
